cache: bundler
rvm:
  - 2.5.3
  - 2.6.5
  - 2.7.0
  - ruby-head
gemfile:
  - gemfiles/Gemfile-rails-5-2
  - gemfiles/Gemfile-rails-6-0
  - gemfiles/Gemfile-rails-main
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
